# Generated by Django 5.0.6 on 2024-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Birthdate', models.DateField()),
                ('Phone', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Degree', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=200)),
            ],
        ),
    ]
