# Generated by Django 5.0.6 on 2024-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Birthdate', models.DateField()),
                ('Phone', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Degree', models.CharField(max_length=200)),
                ('Website', models.CharField(blank=True, max_length=200)),
                ('Age', models.IntegerField(default=0)),
                ('myDiscription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mycontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Number', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Othercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCerti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('From', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=200)),
                ('College', models.CharField(max_length=200)),
                ('Startdate', models.CharField(max_length=250)),
                ('Enddate', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Post', models.CharField(max_length=200)),
                ('Phone', models.CharField(blank=True, max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=200)),
                ('Location', models.CharField(blank=True, max_length=200)),
                ('Summary', models.TextField()),
                ('Language', models.ManyToManyField(blank=True, to='Main_app.language')),
            ],
        ),
    ]
