# Generated by Django 5.0.6 on 2024-05-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
