# Generated by Django 4.2.12 on 2024-07-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Website',
        ),
    ]
