# Generated by Django 5.0.6 on 2024-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_about_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='myDiscription',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
