# Generated by Django 5.0.6 on 2024-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0004_alter_about_mydiscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
