# Generated by Django 5.0.6 on 2024-05-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0006_alter_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='Image',
        ),
    ]
