# Generated by Django 5.0.6 on 2024-05-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0007_rename_image_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Number', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Othercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
