# Generated by Django 5.0.6 on 2024-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0009_alter_about_mydiscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='myDiscription',
            field=models.TextField(),
        ),
    ]
