# Generated by Django 5.0.6 on 2024-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0012_resume_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='fileName',
            field=models.CharField(max_length=200),
        ),
    ]
