# Generated by Django 5.0.6 on 2024-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0014_alter_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary', models.TextField()),
                ('Post', models.CharField(max_length=200)),
                ('Skills', models.CharField(max_length=200)),
                ('Lamguage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCerti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('From', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=200)),
                ('College', models.CharField(max_length=200)),
                ('Startdate', models.DateField()),
                ('Enddate', models.DateField()),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
