# Generated by Django 5.0.6 on 2024-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0017_remove_resumeabout_lamguage_resumeabout_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='Enddate',
            field=models.DateField(default='present'),
        ),
    ]
