# Generated by Django 5.0.6 on 2024-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0018_alter_resumeeducation_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='Enddate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resumeeducation',
            name='Startdate',
            field=models.CharField(max_length=250),
        ),
    ]
