# Generated by Django 5.0.6 on 2024-05-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0019_alter_resumeeducation_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeabout',
            name='Email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumeabout',
            name='Location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumeabout',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumeabout',
            name='Phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
