# Generated by Django 5.0.6 on 2024-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0020_resumeabout_email_resumeabout_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='resumeabout',
            name='Language',
        ),
        migrations.AddField(
            model_name='resumeabout',
            name='Language',
            field=models.ManyToManyField(blank=True, to='Main_app.language'),
        ),
    ]
